language: ruby

rvm:
  - 2.5.7

gemfile:
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile

before_install:
  # - yes | gem update --system --force
  # - gem install bundler
  - bundle install
  - echo "$(pwd)"
  - bundle exec appraisal install
